version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"  # Bind frontend to localhost
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: production
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 25s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  mailcleaner:
    build:
      context: ./backend/MailCleaner
    container_name: mailcleaner
    volumes:
      - ./backend/MailCleaner/maildir:/app/maildir
      - ./backend/MailCleaner/processed:/app/processed
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
    networks:
      - app-network
    restart: on-failure

  indexer:
    build:
      context: ./backend/Indexer
    container_name: indexer
    depends_on:
      rabbitmq:
        condition: service_healthy
      mssql:
        condition: service_started
      mailcleaner:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      SQL_HOST: mssql
      SQL_PORT: "1433"
      SQL_USER: sa
      SQL_PASSWORD: "Your_password123"
    ports:
      - "5000:5000"  # Bind indexer to localhost
    networks:
      - app-network
    restart: on-failure

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network

  # Prometheus for metrics scraping
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - mailcleaner
    networks:
      - app-network


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3030:3000"
    depends_on:
      - prometheus
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mssql_data:
